### ISSUE TITLE
`make dkms` creates directory suffixed with the current time rather than the commit time

### ISSUE THREAD

**Issue by jaythegreatman** [frankcrawford/it87#23]
https://github.com/frankcrawford/it87/blob/043eae2cad7ee26f05a38b5602dce3c207bf974a/Makefile#L32
Because the dollar sign is not escaped by double it, make is treat the `$(git show -s --format=%ci HEAD)` part as a variable rather than pass it to shell.

**Comment by frankcrawford** [comment]
Thanks, I'll look at it.

**Comment by frankcrawford** [comment]
I've update the Makefile to correctly look up the commit time and pushed the commit.

**Comment by frankcrawford** [comment]
Closed.
