### ISSUE TITLE
Use UTC when creating DRIVER_VERSION

### ISSUE THREAD

**Issue by jaythegreatman** [frankcrawford/it87#25]
The `date` command is used when creating `DRIVER_VERSION` in the `Makefile` and `dkms-install.sh`. By default, `date` uses the local time zone. If the local time zone is changed, sometimes date could go back one day. In this case, if there exists a version created against an earlier commit on the same day as the current commit, its date will appear to be more recent than the current version.

`date -u` prints the date in UTC.

**Comment by frankcrawford** [comment]
Good point,  I'll look at doing an update for it in the near future.

**Comment by frankcrawford** [comment]
Fixed in latest commit.
