### ISSUE TITLE
it8628

### ISSUE THREAD

**Issue by denji** [frankcrawford/it87#28]
Gigabyte X470 Gaming 7 https://gist.github.com/nijave/53eb41a4aa79f754f1ba6fdeaa32c0dd

```
chip "it8628-isa-0a40"
    label temp1 "System 1"
    label temp2 "Chipset"
    label temp3 "CPU Socket"
    label temp4 "PCIEX16"
    label temp5 "VRM MOS"
    label temp6 "VSOC MOS"
    label in0 "CPU Vcore"
    label in1 "+3.3V"
    label in2 "+12V"
    label in3 "+5V"
    label in4 "CPU VCORE SoC"
    label in5 "CPU VDDP"
    label in6 "DRAM CH(A/B)"
#   label in7 "3VSB"
#   label in8 "CMOS Voltage Battery"
    label fan1 "CPU_FAN"
    label fan2 "SYS_FAN1"
    label fan3 "SYS_FAN2"
    label fan4 "SYS_FAN3"
    label fan5 "CPU_OPT"
#   compute temp3 @+0.5,@+0.5
    compute in1 @*1.65,@*1.65
    compute in2 @*6,@*6
    compute in3 @*2.5,@*2.5
    set in0_min 0.35
    set in0_max 1.45
    set in1_min 3.3 * 0.97
    set in1_max 3.3 * 1.03
    set in2_min 12 * 0.97
    set in2_max 12 * 1.03
    set in3_min 5 * 0.97
    set in3_max 5 * 1.03
    set in4_min 0.9
    set in4_max 1.26
    set in5_min 0.9 * 0.95
    set in5_max 0.9 * 1.05
    set in6_min 1.1
    set in6_max 1.6
    ignore temp2
    #label temp2 "EC_TEMP1" # Will show -55C if open circuit (no thermistor plugged in)
    label intrusion0 "Chassis Intrusion"
    #ignore intrusion0
```

### `/etc/modules-load.d/it87.conf`
```
it87
options it87 force_id=0x8628
```

### GRUB & systemd-boot (`/etc/kernel/cmdline`)
```
acpi_enforce_resources=lax
```

~~GIGABYTE X570 Aorus Master: https://github.com/arcnmx/home/blob/master/hw/x570am/default.nix#L16-L54~~

**Comment by frankcrawford** [comment]
@denji which version of the it87 modules are those commands for, the one in the kernel mainline, or the one from this repo?

The reason I ask is that this repo should already detect chipID 0x8628 and handle it correctly without the need for a force option.  Further the option `acpi_enforce_resources=lax` is not needed, and rather should be replaced by `option it87 ignore_resource_conflict=true`.

In fact both items are true even for recent mainline kernels.

However, if this is really to get the chipsets working for a Gigabyte X570 Aorus Master, this repo handles it automatically, as it matches the two chipset, IT8688E + IT8792E/IT8795E, used on that board, but the mainline kernel doesn't yet.

So, please add a few details about what you issue you are facing so we can sort it out.

Frank
